# Generated by Django 3.2.22 on 2023-11-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='哪年的预算')),
                ('mpname', models.CharField(max_length=128, verbose_name='使用哪个项目的预算')),
                ('pnamel', models.JSONField(verbose_name='使用该项目预算的有哪些项目')),
            ],
            options={
                'verbose_name_plural': '年度项目标注预算使用设置',
                'db_table': 'ybudget',
            },
        ),
    ]
