# Generated by Django 3.2.22 on 2023-11-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_ybudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ybudget',
            name='mpname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.project', to_field='pname', verbose_name='使用哪个项目的预算'),
        ),
    ]
