# Generated by Django 3.2.22 on 2023-11-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_ybudget_mpname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slessvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slvender', models.CharField(max_length=128, unique=True, verbose_name='Snorlax 供应商名')),
                ('essvender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.supplier', verbose_name='ESS 供应商名')),
            ],
            options={
                'verbose_name_plural': 'Snorlax 供应商名表',
                'db_table': 'slvender',
            },
        ),
        migrations.CreateModel(
            name='Slesspn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slpname', models.CharField(max_length=100, unique=True, verbose_name='Snorlax 项目名')),
                ('esspname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.project', verbose_name='项目名')),
            ],
            options={
                'verbose_name_plural': 'Snorlax 项目名字表',
                'db_table': 'slproject',
            },
        ),
    ]
