# Generated by Django 3.2.22 on 2024-02-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_slesspn_slessvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='pname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget_pname', to='service.project', verbose_name='项目名字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliertask',
            name='pname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliertask_pname', to='service.project', verbose_name='项目名字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliertask',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliertask_vendor', to='service.supplier', verbose_name='供应商'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ybudget',
            name='pname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ybudget_pname', to='service.project', verbose_name='使用哪个项目的预算'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='proname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_proname', to='service.project', to_field='pname', verbose_name='项目名字'),
        ),
        migrations.AlterField(
            model_name='suppliertask',
            name='proname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliertask_proname', to='service.project', to_field='pname', verbose_name='项目名字'),
        ),
        migrations.AlterField(
            model_name='suppliertask',
            name='wb_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliertask_wb_name', to='service.supplier', to_field='name', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='ybudget',
            name='mpname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ybudget_mpname', to='service.project', to_field='pname', verbose_name='使用哪个项目的预算'),
        ),
    ]
