# Generated by Django 3.2.22 on 2024-02-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20240224_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='proname',
        ),
        migrations.RemoveField(
            model_name='suppliertask',
            name='proname',
        ),
        migrations.RemoveField(
            model_name='suppliertask',
            name='wb_name',
        ),
        migrations.RemoveField(
            model_name='ybudget',
            name='mpname',
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.CharField(default='13edab8e-d2db-11ee-b321-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.project', verbose_name='项目名字'),
        ),
        migrations.AlterField(
            model_name='gstask',
            name='id',
            field=models.CharField(default='13edab89-d2db-11ee-985c-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='13edab8a-d2db-11ee-a4fa-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slesspn',
            name='id',
            field=models.CharField(default='13edab90-d2db-11ee-a92e-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slessvd',
            name='id',
            field=models.CharField(default='13edab91-d2db-11ee-815b-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.CharField(default='13edab8c-d2db-11ee-b963-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suppliertask',
            name='id',
            field=models.CharField(default='13edab8d-d2db-11ee-80b0-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suppliertask',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.project', verbose_name='项目名字'),
        ),
        migrations.AlterField(
            model_name='suppliertask',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='taskkind',
            name='id',
            field=models.CharField(default='13edab8b-d2db-11ee-ba49-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ybudget',
            name='id',
            field=models.CharField(default='13edab8f-d2db-11ee-bdb7-b025aa3cafdf', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ybudget',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.project', verbose_name='使用哪个项目的预算'),
        ),
    ]
